spring:
  application:
    name: Ballit
  datasource:
    url: jdbc:postgresql://localhost:5432/ballit_db
    username: ballit_championship
    password: a12345678
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
